name: test step

on:
    push:
        branches:
            - master
    workflow_dispatch: ~

jobs:
    test_job:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout
                uses: actions/checkout@master
            -
                name: Setup node env
                uses: actions/setup-node@v2
                with:
                    node-version: 16
            -
                name: Install dependencies
                run: npm ci
            -
                name: Use alpine docker image
                uses: docker://wolfgangdrescher/humlib:1.1.1
            -
                name: Fetch lyrics from humdrum files
                run: npm run lyrics
            -
                name: Run humdrum commands
                run: |
                    which cint
                    which shed
                    hint kern/01-beatus-vir.krn
                    cint kern/01-beatus-vir.krn
