name: test step

on:
    push:
        branches:
            - master
    workflow_dispatch: ~

jobs:
    test_job:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout
                uses: actions/checkout@master
            -
                name: Setup node env
                uses: actions/setup-node@v2
                with:
                    node-version: 16
            -
                name: Install dependencies
                run: npm ci
            -
                name: Use inline docker image
                uses: docker://wolfgangdrescher/humlib
            -
                name: Build metadata and write meta.json
                run: npm run build
            -
                name: Commit changes
                run: |
                    git config --global user.name "Wolfgang Drescher"
                    git config --global user.email "drescher.wolfgang+git@gmail.com"
                    git diff --quiet && git diff --staged --quiet || git commit -am "Action: Build metadata and write meta.json"
                    git push
            -
                name: Run humdrum commands
                run: |
                    which cint
                    which shed
                    hint kern/01-beatus-vir.krn
                    cint kern/01-beatus-vir.krn
