name: test step

on:
    push:
        branches:
            - master
    workflow_dispatch: ~

jobs:
    test_job:
        runs-on: ubuntu-latest
        container: wolfgangdrescher/humlib:latest

        steps:
            -
                name: Checkout
                uses: actions/checkout@master
            -
                name: Run humdrum commands
                run: |
                    which cint
                    which shed
                    hint 01-beatus-vir.krn
                    cint 01-beatus-vir.krn
