name: test step

on:
    push:
        branches:
            - master
    workflow_dispatch: ~

jobs:
    test_job:
        runs-on: ubuntu-latest
        container: wolfgangdrescher/humdrum

        steps:
            -
                name: Run humdrum commands
                run: hint 01-beatus-vir.krn
